-- ============================================
-- V1: Create core tables
-- ============================================

CREATE TABLE product (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    value NUMBER(19,2) NOT NULL,
    CONSTRAINT uk_product_name UNIQUE (name)
);

CREATE TABLE raw_material (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    stock_quantity NUMBER(19,4) NOT NULL,
    CONSTRAINT uk_raw_material_name UNIQUE (name),
    CONSTRAINT ck_raw_material_stock CHECK (stock_quantity >= 0)
);

CREATE TABLE product_raw_material (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER(19) NOT NULL,
    raw_material_id NUMBER(19) NOT NULL,
    quantity NUMBER(19,4) NOT NULL,
    CONSTRAINT fk_prm_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
    CONSTRAINT fk_prm_raw_material FOREIGN KEY (raw_material_id) REFERENCES raw_material(id) ON DELETE CASCADE,
    CONSTRAINT uk_prm_product_raw_material UNIQUE (product_id, raw_material_id),
    CONSTRAINT ck_prm_quantity CHECK (quantity > 0)
);
